const menu = {
    list() {
        return [
    {
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"管理员管理",
                        "menuJump":"列表",
                        "tableName":"users"
                    }
                ],
                "menu":"管理员管理"
            }
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "导入导出",
			                "删除"
			            ],
			            "menu":"教师管理",
			            "menuJump":"列表",
			            "tableName":"jiaoshi"
			        }
			    ],
			    "menu":"教师管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "导入导出",
			                "删除"
			            ],
			            "menu":"学生管理",
			            "menuJump":"列表",
			            "tableName":"yonghu"
			        }
			    ],
			    "menu":"学生管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "审核",
			                "删除"
			            ],
			            "menu":"课题选择管理",
			            "menuJump":"列表",
			            "tableName":"ketixuanze"
			        }
			    ],
			    "menu":"课题选择管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "删除"
			            ],
			            "menu":"课题申请管理",
			            "menuJump":"列表",
			            "tableName":"ketishenqing"
			        }
			    ],
			    "menu":"课题申请管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "删除"
			            ],
			            "menu":"学生选题管理",
			            "menuJump":"列表",
			            "tableName":"wodeketi"
			        }
			    ],
			    "menu":"学生选题管理"
			}
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"公告信息管理",
                        "menuJump":"列表",
                        "tableName":"news"
                    }
                ],
                "menu":"公告信息管理"
            }
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "删除",
			                "修改"
			            ],
			            "menu":"班级管理",
			            "menuJump":"列表",
			            "tableName":"dictionaryBanji"
			        }
			        ,
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "删除",
			                "修改"
			            ],
			            "menu":"课题类型管理",
			            "menuJump":"列表",
			            "tableName":"dictionaryKetixuanze"
			        }
			        ,
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "删除",
			                "修改"
			            ],
			            "menu":"课题来源管理",
			            "menuJump":"列表",
			            "tableName":"dictionaryLaiyuan"
			        }
			        ,
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "删除",
			                "修改"
			            ],
			            "menu":"公告类型管理",
			            "menuJump":"列表",
			            "tableName":"dictionaryNews"
			        }
			        ,
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "删除",
			                "修改"
			            ],
			            "menu":"专业管理",
			            "menuJump":"列表",
			            "tableName":"dictionaryZhuanye"
			        }
			    ],
			    "menu":"基础数据管理"
			}
        ],
        "frontMenu":[],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"否",
        "hasFrontRegister":"否",
        "roleName":"管理员",
        "tableName":"users"
    },
	{
	    "backMenu":[
	        {
			    "child":[
			        {
			            "buttons":[
			                "查看"
			            ],
			            "menu":"学生管理",
			            "menuJump":"列表",
			            "tableName":"yonghu"
			        }
			    ],
			    "menu":"学生管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"课题选择管理",
			            "menuJump":"列表",
			            "tableName":"ketixuanze"
			        }
			    ],
			    "menu":"课题选择管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "审核"
			            ],
			            "menu":"课题申请管理",
			            "menuJump":"列表",
			            "tableName":"ketishenqing"
			        }
			    ],
			    "menu":"课题申请管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "打分",
			                "审核"
			            ],
			            "menu":"学生选题管理",
			            "menuJump":"列表",
			            "tableName":"wodeketi"
			        }
			    ],
			    "menu":"学生选题管理"
			}
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"公告信息管理",
	                    "menuJump":"列表",
	                    "tableName":"news"
	                }
	            ],
	            "menu":"公告信息管理"
	        }
	    ],
	    "frontMenu":[],
	    "hasBackLogin":"是",
	    "hasBackRegister":"否",
	    "hasFrontLogin":"否",
	    "hasFrontRegister":"否",
	    "roleName":"教师",
	    "tableName":"jiaoshi"
	},
	{
	    "backMenu":[
	        {
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "选题"
			            ],
			            "menu":"课题选择管理",
			            "menuJump":"列表",
			            "tableName":"ketixuanze"
			        }
			    ],
			    "menu":"课题选择管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看"
			            ],
			            "menu":"课题申请管理",
			            "menuJump":"列表",
			            "tableName":"ketishenqing"
			        }
			    ],
			    "menu":"课题申请管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
							"申请答辩",
							"上传文件"
			            ],
			            "menu":"我的课题管理",
			            "menuJump":"列表",
			            "tableName":"wodeketi"
			        }
			    ],
			    "menu":"我的课题管理"
			}
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"公告信息管理",
	                    "menuJump":"列表",
	                    "tableName":"news"
	                }
	            ],
	            "menu":"公告信息管理"
	        }
	    ],
	    "frontMenu":[],
	    "hasBackLogin":"是",
	    "hasBackRegister":"否",
	    "hasFrontLogin":"否",
	    "hasFrontRegister":"否",
	    "roleName":"学生",
	    "tableName":"yonghu"
	}
]
    }
}
export default menu;
